name: Chisel
version: 0.1.6
authors: [oshcon]
softdepend: [NoCheatPlus]
website: http://doodcraft.net/
main: net.doodcraft.oshcon.bukkit.chisel.ChiselPlugin

commands:
  chisel:
    description: Base command

permissions:
  chisel.*:
    description: Grants all plugin permission nodes
    default: OP
  chisel.command.chisel:
    description: Allows players to use /chisel
    default: OP
  chisel.command.reload:
    description: Allows players to use /chisel reload
    default: OP
  chisel.command.give:
    description: Allows players to use /chisel give
    default: OP
  chisel.craft:
    description: Allows the player to craft the chisel
    default: true
  chisel.use:
    description: Allows the player to use the chisel
    default: true